name: Test

on:
  pull_request:
    branches:
      - development

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Set up Python
        uses: actions/setup-python@v5.4.0
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Install tox
        run: pip install tox

      - name: Copy config file
        run: cp local_settings.cfg.example local_settings.cfg

      - name: Run tox
        run: tox